config/routes.rb
Sherwood::Application.routes.draw do

  get 'contact' => 'pages#contact'
  get 'about' => 'pages#about'
  get 'resume' => 'pages#resume'

  root :to => "pages#home"

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def contact
  end

  def about
  end

	def resume
	  # pdf_filename = File.join(Rails.root, "tmp/Carlos.Resume.2013.pdf")
	  # send_file(pdf_filename, :filename => "Carlos.Resume.2013.pdf", :disposition => 'inline', :target => "_blank" )
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= link_to "Sherwood", root_path %>
    by <%= link_to "Carlos Cheung", about_path %>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact",   contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner collapse navbar-collapse navbar-ex1-collapse">
    <div class="container">
      <%= link_to "Sherwood", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-left">
          <li ><%= link_to "About", about_path %></li>
          <li><%= link_to "Contact", contact_path %></li>
          <li><%= link_to "Resume", resume_path %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sherwood</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <%= render 'layouts/header' %>

		<div id="wrap">
		  <div id="main" class="container clear-top">
					<%= yield %>
		  </div>
		</div>    

    <%= render 'layouts/footer' %>
</body>
</html>

app/views/pages/about.html.erb
<div class="row-fluid">
   <div class="span12 pagination-centered">
   		<%= image_tag("zaarly.jpeg", :alt => "myself") %>
   </div>
</div>
<h1 class="about"><strong>The name's Carlos ...<br> Carlitos, Charlie, and anything else similar.</strong></h1>

<h2>More about me:</h2>
<p>Mostly known for Sales and Marketing. Self taught programmer (Ruby on Rails, HTML, CSS). Looking to learn and grow. Georgetown Univ. Undergrad Business Program.</p>

<h2>Blogging:</h2>
<h2><%= link_to "Medium", "https://medium.com/@CarloskCheung", :class => "linkmargin", :target => "_blank" %></h2>

app/views/pages/contact.html.erb
<h1>Digital Footprint</h1>

<div>
  <h2 class = "pagination-centered">
	 <%= link_to "Linkedin", "http://www.linkedin.com/in/carloscheung", :class => "linkmargin", :target => "_blank" %> 
	 <%= link_to "Twitter", "https://twitter.com/CarloskCheung", :class => "linkmargin", :target => "_blank" %>     
	 <%= link_to "Facebook", "https://www.facebook.com/cheungcarlos", :class => "linkmargin", :target => "_blank" %>  
	 <%= link_to "Instagram", "http://instagram.com/carloskcheung/", :class => "linkmargin", :target => "_blank" %>    
	 <%= link_to "GitHub", "https://github.com/carloskcheung", :class => "linkmargin", :target => "_blank" %>
	</h2>
</div>




<div>
    <iframe height="517" allowTransparency="true" frameborder="0" scrolling="no" style="width:100%;border:none"  src="http://cc653.wufoo.com/embed/q7x2x3/"><a href="http://cc653.wufoo.com/forms/q7x2x3/">Fill out my Wufoo form!</a></iframe>
</div>

app/views/pages/home.html.erb
<div class="row-fluid">
   <div class=""> <%= image_tag 'Gtown3.jpg' %> </div>
</div>

<h1 class="ontop"><strong>"Learn to work then you'll always work;<br> Work to learn then you'll always learn"</strong></h1>  

app/views/pages/resume.html.erb
<h1> Coming Soon...</h1>